global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:

  - job_name: 'otel-collector'
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets: ['otel-collector:8889']
      - targets: ['otel-collector:8888']