server.port: 8084
spring:
  kafka:
    consumer:
      group-id: tpd-loggers
      auto-offset-reset: earliest
    # change this property if you are using your own
    # Kafka cluster or your Docker IP is different
    bootstrap-servers: kafka:9092

tpd:
  topic-name: advice-topic

management.endpoint.metrics.enabled: true
management.endpoints.web.exposure.include: prometheus
management.endpoint.prometheus.enabled: true
management.metrics.export.prometheus.enabled: true