{
 "title": "Monitoring",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Business metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Clicks on product",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(clicks_on_product_count[$__rate_interval])) by (produto)",
     "legendFormat": "{{produto}}"
    }
   ]
  },
  {
   "title": "Access by branch",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 1 },
   "targets": [
    {
     "expr": "sum(sum_over_time(default_client_info[$__range])) by (clientBranch)",
     "legendFormat": "{{clientBranch}}"
    }
   ]
  },
  {
   "title": "Access by OS",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(default_device_info[$__range])) by (clientOsName)",
     "legendFormat": "{{clientOsName}}"
    }
   ]
  },
  {
   "title": "Access by brand",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(default_device_info[$__range])) by (brand)",
     "legendFormat": "{{brand}}"
    }
   ]
  },
  {
   "title": "Access over the world",
   "type": "geomap",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 15 },
   "targets": [
    { "expr": "default_device_info{}" }
   ]
  },
  {
   "title": "Infrastructure metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests status by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum(sum_over_time(http_server_duration_count[$__rate_interval])) by (http_route, http_status_code)",
     "legendFormat": "{{http_status_code}},  {{http_route}}"
    }
   ]
  },
  {
   "title": "Kafka lag",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 8, "y": 23 },
   "targets": [
    {
     "expr": "sum(default_kafka_consumer_records_lag) by (topic)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests by status",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 5, "x": 17, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(http_server_duration_count[$__rate_interval])) by (http_route, http_status_code)",
     "legendFormat": "{{http_status_code}}"
    }
   ]
  },
  {
   "title": "Log ingest",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 22, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(rate({job=\"otel-collector\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Log info",
   "type": "logs",
   "gridPos": { "h": 10, "w": 22, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "{job=\"otel-collector\"}"
    }
   ]
  }
 ]
}